- name: Apply CIS Benchmark to Ubuntu 20.04 Servers
  hosts: all
  become: yes
  vars:
    # Ensure system is up-to-date
    apt_update_cache: yes
    apt_upgrade: dist
    apt_autoremove: yes

  tasks:
    # Other tasks...

    - name: Ensure core dumps are disabled
      lineinfile:
        path: /etc/security/limits.conf
        regexp: '^* soft core'
        line: '* soft core 0'

    - name: Configure auditd to ensure auditing is enabled
      package:
        name: auditd
        state: present

    - name: Ensure auditd service is running
      service:
        name: auditd
        state: started
        enabled: yes

    - name: Configure audit rules
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        create: yes
        line: "{{ item }}"
      loop:
        - '-w /etc/passwd -p wa -k identity'
        - '-w /etc/shadow -p wa -k identity'
        - '-w /etc/group -p wa -k identity'

    - name: Ensure filesystem is mounted with noexec, nodev, nosuid options
      mount:
        path: "{{ item.path }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        state: mounted
      loop:
        - { path: /tmp, fstype: ext4, opts: 'nodev,noexec,nosuid' }
        - { path: /var/tmp, fstype: ext4, opts: 'nodev,noexec,nosuid' }

    - name: Set system umask to 027 for new files
      lineinfile:
        path: /etc/profile
        regexp: '^umask'
        line: 'umask 027'

    - name: Configure password expiration and complexity requirements
      lineinfile:
        path: /etc/login.defs
        regexp: '^{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
      loop:
        - { key: PASS_MAX_DAYS, value: '90' }
        - { key: PASS_MIN_DAYS, value: '7' }
        - { key: PASS_MIN_LEN, value: '14' }
        - { key: PASS_WARN_AGE, value: '7' }

    - name: Ensure PAM is configured for password complexity
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
      loop:
        - { key: password requisite pam_pwquality.so, value: 'retry=3 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1' }

    - name: Ensure that the system is configured to prevent users from setting empty passwords
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
      loop:
        - { key: password requisite pam_pwquality.so, value: 'enforce_for_root' }
