---
- name: Run OpenSCAP Compliance Scan
  hosts: all
  become: yes
  tasks:

    - name: Ensure OpenSCAP is installed
      apt:
        name: openscap-scanner
        state: present
      tags: openscap

    - name: Download CIS Ubuntu 20.04 Benchmark
      get_url:
        url: "https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.focal.cis.xml.bz2"
        dest: "/tmp/cis_benchmark.xml.bz2"
      tags: openscap

    - name: Decompress the CIS Benchmark XML
      command: "bunzip2 /tmp/cis_benchmark.xml.bz2"
      args:
        creates: "/tmp/cis_benchmark.xml"
      tags: openscap

    - name: Run OpenSCAP scan using CIS profile
      command: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_cis
        --report /tmp/openscap_report.html
        /tmp/cis_benchmark.xml
      tags: openscap

    - name: Fetch the OpenSCAP report to the Ansible controller
      fetch:
        src: /tmp/openscap_report.html
        dest: "{{ playbook_dir }}/reports/{{ inventory_hostname }}-openscap_report.html"
        flat: yes
      tags: openscap

    - name: Clean up the benchmark file on the target
      file:
        path: "/tmp/cis_benchmark.xml"
        state: absent
      tags: openscap

    - name: Clean up the report file on the target
      file:
        path: "/tmp/openscap_report.html"
        state: absent
      tags: openscap
