---
- name: Power off hosts
  hosts: all
  become: yes
  tasks:
    - name: Power off the host
      community.general.shutdown:
        power_off: yes
        timeout: 120
      register: shutdown_result

    - name: Display shutdown result
      debug:
        msg: "Host {{ inventory_hostname }} is powering off."
      when: shutdown_result is success
