---
- name: Power off hosts
  hosts: all
  become: yes
  tasks:
    - name: Power off the host
      community.general.shutdown:
        shutdown: yes
        timeout: 120
      register: poweroff_result

    - name: Display power off result
      debug:
        msg: "Host {{ inventory_hostname }} is powering off."
      when: poweroff_result is success
