---
- name: Reboot all hosts
  hosts: all
  become: yes
  tasks:
    - name: Reboot the host
      ansible.builtin.reboot:
        reboot_timeout: 300  # Time to wait for the reboot to complete, in seconds
        test_command: whoami  # Command to check if the host is back online
      register: reboot_result

    - name: Display reboot result
      debug:
        msg: "Host {{ inventory_hostname }} rebooted successfully."
      when: reboot_result is success
