---
- name: Start VirtualBox VMs
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ensure VirtualBox is installed
      ansible.builtin.apt:
        name: virtualbox
        state: present
      become: yes
      tags: install

    - name: Check if VBoxManage is available
      ansible.builtin.command: which VBoxManage
      register: vboxmanage_path
      changed_when: false
      failed_when: vboxmanage_path.rc != 0

    - name: Power up the VM using VBoxManage
      ansible.builtin.command: >
        "{{ vboxmanage_path.stdout }}" startvm "{{ inventory_hostname }}" --type headless
      register: vm_start_output
      ignore_errors: yes
      when: vboxmanage_path.rc == 0

    - name: Display VM startup output
      ansible.builtin.debug:
        var: vm_start_output.stdout
      when: vboxmanage_path.rc == 0

    - name: Ensure VM is running
      ansible.builtin.command: >
        "{{ vboxmanage_path.stdout }}" showvminfo "{{ inventory_hostname }}" | grep -q "running (since"
      register: vm_running
      ignore_errors: yes
      when: vboxmanage_path.rc == 0

    - name: Notify if VM failed to start
      ansible.builtin.fail:
        msg: "Failed to start the VM {{ inventory_hostname }}"
      when:
        - vm_running.rc != 0
        - vboxmanage_path.rc == 0
