---
- name: Start VirtualBox VMs
  hosts: all
  gather_facts: no
  tasks:
    - name: Power up the VM using VBoxManage
      ansible.builtin.command: >
        VBoxManage startvm "{{ inventory_hostname }}" --type headless
      register: vm_start_output
      ignore_errors: yes

    - name: Display VM startup output
      ansible.builtin.debug:
        var: vm_start_output.stdout

    - name: Ensure VM is running
      ansible.builtin.command: >
        VBoxManage showvminfo "{{ inventory_hostname }}" | grep -q "running (since"
      register: vm_running
      ignore_errors: yes

    - name: Notify if VM failed to start
      ansible.builtin.fail:
        msg: "Failed to start the VM {{ inventory_hostname }}"
      when: vm_running.rc != 0
