---
- hosts: all
  tasks:
          - name: Install apache2 server
            apt:
              name: 
                - apache2
                - curl
              state: present
          - name: Change Web Page
            shell: |
               echo "This is Webserver on `hostname`" > /var/www/html/index.html
          - name: Start Apache2
            service:
              name: apache2
              state: started
              enabled: yes
          - name: Test Apache2
            shell: |
               curl http://localhost
            register: apache2result

          - name: Print apache2 test result
            debug:
                    msg: "{{ apache2result.stdout }}"
