---
- name: Generate and Apply SCAP Remediation
  hosts: all
  become: yes  # Use become to execute commands with elevated privileges
  tasks:
    - name: Ensure OpenSCAP is installed
      ansible.builtin.apt:
        name: libopenscap8
        state: present

    - name: Ensure SCAP Security Guide is installed
      ansible.builtin.apt:
        name: ssg-debderived
        state: present

    - name: Generate SCAP remediation file
      ansible.builtin.command: >
        oscap xccdf generate fix
        --profile xccdf_org.ssgproject.content_profile_cis_level1_server
        --template urn:xccdf:fix:script:ansible
        --output /tmp/{{ inventory_hostname }}-remediation.yml
        /usr/share/xml/scap/ssg/content/scap-security-guide-0.1.69/ssg-ubuntu2004-ds-1.2.xml
      register: generate_remediation
      ignore_errors: yes

    - name: Print remediation generation status
      ansible.builtin.debug:
        var: generate_remediation.rc

    - name: Check if the remediation file was generated
      ansible.builtin.stat:
        path: /tmp/{{ inventory_hostname }}-remediation.yml
      register: remediation_file

    - name: Fail if the remediation file was not created
      ansible.builtin.fail:
        msg: "The remediation file /tmp/{{ inventory_hostname }}-remediation.yml was not created."
      when: not remediation_file.stat.exists

    - name: Apply the remediation file
      ansible.builtin.command: >
        ansible-playbook /tmp/{{ inventory_hostname }}-remediation.yml
      ignore_errors: yes

    - name: Print remediation application status
      ansible.builtin.debug:
        msg: "Remediation applied with status {{ ansible_status.rc }}"

    - name: Cleanup remediation file
      ansible.builtin.file:
        path: /tmp/{{ inventory_hostname }}-remediation.yml
        state: absent
