---
- name: Generate and Apply SCAP Remediation
  hosts: all
  tasks:
    - name: Ensure OpenSCAP is installed
      ansible.builtin.apt:
        name: libopenscap8
        state: present

    - name: Ensure SCAP Security Guide is installed
      ansible.builtin.apt:
        name: ssg-debderived
        state: present

    - name: Generate SCAP remediation file
      ansible.builtin.command: >
        oscap xccdf generate fix
        --profile xccdf_org.ssgproject.content_profile_cis_level2_server
        --template urn:xccdf:fix:script:ansible
        --output /tmp/{{ inventory_hostname }}-remediation.yml
        /usr/share/xml/scap/ssg/content/scap-security-guide-0.1.69/ssg-ubuntu2004-ds-1.2.xml
      register: generate_remediation
      ignore_errors: yes

    - name: Print remediation generation status
      ansible.builtin.debug:
        var: generate_remediation.rc

    - name: Slurp the remediation file from the host
      ansible.builtin.slurp:
        src: /tmp/{{ inventory_hostname }}-remediation.yml
      register: slurp_remediation

    - name: Create reports directory on the master node
      ansible.builtin.file:
        path: /home/reports
        state: directory
        mode: '0755'
      delegate_to: master
      run_once: true

    - name: Transfer the remediation file to the master node
      ansible.builtin.copy:
        content: "{{ slurp_remediation.content | b64decode }}"
        dest: /home/reports/{{ inventory_hostname }}-remediation.yml
        mode: '0644'
      delegate_to: master

    # Apply the remediation back to the original host from the master
    - name: Apply the remediation file from the master to the host
      ansible.builtin.command: >
        ansible-playbook /home/reports/{{ inventory_hostname }}-remediation.yml
      delegate_to: master
      ignore_errors: yes

    - name: Cleanup local remediation file on the host
      ansible.builtin.file:
        path: /tmp/{{ inventory_hostname }}-remediation.yml
        state: absent

    - name: Cleanup remediation file on the master node
      ansible.builtin.file:
        path: /home/reports/{{ inventory_hostname }}-remediation.yml
        state: absent
      delegate_to: master
