---
- name: Run OpenSCAP and Apply Remediation
  hosts: all
  tasks:
    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install OpenSCAP
      ansible.builtin.apt:
        name: libopenscap8
        state: present

    - name: Confirm installation of OpenSCAP
      ansible.builtin.command: which oscap
      register: oscap_location
      ignore_errors: yes

    - name: Install SCAP security guide for Debian-based OS
      ansible.builtin.apt:
        name: ssg-debderived
        state: present

    - name: Ensure the target directory for SCAP Security Guide exists
      ansible.builtin.file:
        path: /usr/share/xml/scap/ssg/content/
        state: directory
        mode: '0755'

    - name: Check if SCAP Security Guide has already been downloaded and unzipped
      ansible.builtin.stat:
        path: /usr/share/xml/scap/ssg/content/.scap_security_guide_installed
      register: scap_guide_installed

    - name: Download the latest SCAP Security Guide
      ansible.builtin.get_url:
        url: https://github.com/ComplianceAsCode/content/releases/download/v0.1.69/scap-security-guide-0.1.69.zip
        dest: /tmp/scap-security-guide-0.1.69.zip
      when: scap_guide_installed.stat.exists == false

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: Unzip the SCAP Security Guide
      ansible.builtin.unarchive:
        src: /tmp/scap-security-guide-0.1.69.zip
        dest: /usr/share/xml/scap/ssg/content/
        remote_src: yes
      when: scap_guide_installed.stat.exists == false

    - name: Mark SCAP Security Guide as installed
      ansible.builtin.file:
        path: /usr/share/xml/scap/ssg/content/.scap_security_guide_installed
        state: touch
      when: scap_guide_installed.stat.exists == false

    - name: Display available profiles
      ansible.builtin.command: oscap info /usr/share/xml/scap/ssg/content/scap-security-guide-0.1.69/ssg-ubuntu2004-ds-1.2.xml
      register: profile_info

    - name: Print profile information
      ansible.builtin.debug:
        var: profile_info.stdout
        
    - name: Generate SCAP remediation file
      ansible.builtin.command: >
        oscap xccdf generate fix
        --profile xccdf_org.ssgproject.content_profile_cis_level1_server
        --template urn:xccdf:fix:script:ansible
        --output /home/master/reports/{{ inventory_hostname }}-remediation.yml
        /usr/share/xml/scap/ssg/content/scap-security-guide-0.1.69/ssg-ubuntu2004-ds-1.2.xml
      register: generate_remediation
      ignore_errors: yes

    - name: Print scan result status
      ansible.builtin.debug:
        var: scan_result.rc

    # Apply the generated remediation file to the host
    - name: Apply the remediation generated by OpenSCAP
      ansible.builtin.command: ansible-playbook /home/master/reports/{{ ansible_hostname }}-remediation.yml
      register: remediation_apply_result
      ignore_errors: yes

    - name: Print remediation result status
      ansible.builtin.debug:
        var: remediation_apply_result.rc

    # Clean up temporary files after remediation is applied
    - name: Cleanup generated files
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - "{{ ansible_hostname }}-report.html"
        - "{{ ansible_hostname }}-arf.xml"
        - "{{ ansible_hostname }}-remediation.yml"
