all:
  hosts:
    master:
      ansible_host: 192.168.1.150
  children:
    servers:
      children:
        server1:
          ansible_host: 192.168.1.151
        server2:
          ansible_host: 192.168.1.152
        server3:
          ansible_host: 192.168.1.153
...
